/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScannerTestRouteImport } from './routes/scanner-test'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsEmailRouteImport } from './routes/settings.email'
import { Route as ApiEmailSendTestRouteImport } from './routes/api/email/send-test'
import { Route as ApiPublicHooksSendDueRemindersRouteImport } from './routes/api/public/hooks/send-due-reminders'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerTestRoute = ScannerTestRouteImport.update({
  id: '/scanner-test',
  path: '/scanner-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEmailRoute = SettingsEmailRouteImport.update({
  id: '/settings/email',
  path: '/settings/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSendTestRoute = ApiEmailSendTestRouteImport.update({
  id: '/api/email/send-test',
  path: '/api/email/send-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendDueRemindersRoute =
  ApiPublicHooksSendDueRemindersRouteImport.update({
    id: '/api/public/hooks/send-due-reminders',
    path: '/api/public/hooks/send-due-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner-test': typeof ScannerTestRoute
  '/signup': typeof SignupRoute
  '/settings/email': typeof SettingsEmailRoute
  '/api/email/send-test': typeof ApiEmailSendTestRoute
  '/api/public/hooks/send-due-reminders': typeof ApiPublicHooksSendDueRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner-test': typeof ScannerTestRoute
  '/signup': typeof SignupRoute
  '/settings/email': typeof SettingsEmailRoute
  '/api/email/send-test': typeof ApiEmailSendTestRoute
  '/api/public/hooks/send-due-reminders': typeof ApiPublicHooksSendDueRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner-test': typeof ScannerTestRoute
  '/signup': typeof SignupRoute
  '/settings/email': typeof SettingsEmailRoute
  '/api/email/send-test': typeof ApiEmailSendTestRoute
  '/api/public/hooks/send-due-reminders': typeof ApiPublicHooksSendDueRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/scanner-test'
    | '/signup'
    | '/settings/email'
    | '/api/email/send-test'
    | '/api/public/hooks/send-due-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/scanner-test'
    | '/signup'
    | '/settings/email'
    | '/api/email/send-test'
    | '/api/public/hooks/send-due-reminders'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/scanner-test'
    | '/signup'
    | '/settings/email'
    | '/api/email/send-test'
    | '/api/public/hooks/send-due-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScannerTestRoute: typeof ScannerTestRoute
  SignupRoute: typeof SignupRoute
  SettingsEmailRoute: typeof SettingsEmailRoute
  ApiEmailSendTestRoute: typeof ApiEmailSendTestRoute
  ApiPublicHooksSendDueRemindersRoute: typeof ApiPublicHooksSendDueRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner-test': {
      id: '/scanner-test'
      path: '/scanner-test'
      fullPath: '/scanner-test'
      preLoaderRoute: typeof ScannerTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/email': {
      id: '/settings/email'
      path: '/settings/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof SettingsEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/send-test': {
      id: '/api/email/send-test'
      path: '/api/email/send-test'
      fullPath: '/api/email/send-test'
      preLoaderRoute: typeof ApiEmailSendTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-due-reminders': {
      id: '/api/public/hooks/send-due-reminders'
      path: '/api/public/hooks/send-due-reminders'
      fullPath: '/api/public/hooks/send-due-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendDueRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScannerTestRoute: ScannerTestRoute,
  SignupRoute: SignupRoute,
  SettingsEmailRoute: SettingsEmailRoute,
  ApiEmailSendTestRoute: ApiEmailSendTestRoute,
  ApiPublicHooksSendDueRemindersRoute: ApiPublicHooksSendDueRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
